### ISSUE TITLE
[DRAFT] Affiliation to Corsidia and referral fees

### ISSUE THREAD

**Issue by duarme** [publicv-org/publicv#162]
In order to cover expenses and keep this project going, we need a revenue system, compatible with the project mission. 

The first idea is that we could propose to PubliCV users courses based on the skills they'd like to improve (that they publicly share on their publiCVs, so that we won't use any tracking system). We will propose only courses selected by Corsidia or, in the future, other trusted sources.

When they do find a course that they actually want to enroll in, this will either generate a lead or a sale on Corsidia, and PubliCV will get a proportional referral fee. This fee will need to be better defined but I think that, for most cases, it can be around 50%.

I'm thinking about the best way to accomplish this, I'll update this issue as soon as I have some better-formed ideas 😄

**Comment by darmenise** [comment]
Hi Lara @laLara89, I'd like to invite you to this discussion because you certainly can have a fresh point of view over this.

You are currently developing the biggest online free resource on correct English pronunciation, and an awesome paid course that goes along with it. 

Let's imagine that a PubliCV user, Brigitta, expresses her interest in improving her English Pronunciation inside her _publiCV_ (that's how we call user profiles here 🙂 ).

Currently, skills inside any publiCV are represented as a simple comma-separated list. Something like this, which is taken from [my publiCV](https://duccio.publicv.org):

![CleanShot 2021-07-15 at 09 33 44](https://user-images.githubusercontent.com/794154/125740285-d12379c4-1bfb-4da6-9291-70ac03614c95.png)

Instead, they could become clickable tags.

Now, there are at least 2 use cases for any those tags:

1. You are looking for other people with that skill.
2. You are interested in knowing how to improve that skill.

We could develop an interface that would provide the user with two actions on each skill:

1. Search for other people with this skill => they'll get more search results on PubliCV.
2. Suggestions on how to improve this skill => they'll get an automatically-generated list of suggestions with both free resources and **pre-selected** courses, linking to external resources. We can think about this list as search results, but instead of having publiCVs as results, we get suggestions on how to improve the selected skill.

We already have one trusted source for pre-selected Courses, which is Corsidia, but there is nothing preventing PubliCV from later expand the list of trusted sources, once we define how this kind of partnership should work.

One idea is to define a referral fee. It would be relatively easy to anonymously track whether a visitor came from PubliCV. Back to Brigitta, she could:

- Click on "English pronunciation",
- Click on `5 suggestions on how to improve it`,
- Read the 5 suggestions and click on the one that takes her to your online free resource (we can imagine some sorting algorithm that puts the best suggestions on top),
- Decide to take it one step further, and buy your course.

At this point, being your course sold to Brigitta through Corsidia, there could be a referral fee agreement in place between PubliCV and each trusted source (in this case Corsidia). For instance, Corsidia could pay a 10% referral fee back to PubliCV on each course sold this way.

--------------------

It's worth noting that there are other approaches to an affiliation between PubliCV and trusted sources. For instance, instead of turning the skills into clickable tags, PubliCV could:

- display targeted ads (banners);
- send targeted newsletters.

Provided that one approach doesn't exclude the others, I'd prefer not jumping to those more common ones before having tried something that feels fresher and would probably deliver a better user experience.

**Comment by duarme** [comment]
Duplicate of #236
