### ISSUE TITLE
Confirmed accounts should be allowed to publish their CV's

### ISSUE THREAD

**Issue by vishal-bluebash** [publicv-org/publicv#216]
### Discussed in https://github.com/publicv-org/publicv/discussions/214

<div type='discussions-op-text'>

<sup>Originally posted by **vishal-bluebash** September  8, 2021</sup>
As we are working on anti-spam issues, we should also make sure our database should show genuine CV's which are of confirmed accounts, We should validate, we are allowing job seeker to create CV, decorate it, but they can publish once they confirm their account </div>

**Comment by vishal-bluebash** [comment]
Check discussion for more insights

**Comment by bb-varun** [comment]
User Story:
I want to publish my account after creating CV, so that it can be viewed by Job Providers.

Problem:
There might be many accounts which are inappropriate or fake and their CV's are visible to Job Providers which can be time-wasting. As a Job Provider I only want to see the CV's of the account that are verified. 

Solution:
A user can only Publish their account after verifying it. After clicking on publish button user should get a flash message to verify their account first and then publish it. 

- [ ] Verification mail sent to publish the CV?
- [ ] Created the PR for this issue?
- [ ] Added issue number in the PR?
- [ ] Created demo video?
- [ ] Code Documented/Commented?
