### ISSUE TITLE
Home Page - Last Published CVs looks a bit like Tinder

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#218]
As a recruiting expert, i think we're giving to much attention on the profile Images instead of professional profiles and descriptions.

![Publicv](https://user-images.githubusercontent.com/90318732/133091968-b88ba8f2-d8b4-4b88-a755-6fd0a87d2b1a.PNG)

**POSSIBLE SOLUTION:**

Decrease the size of the headshot and switch it from the left side to the right (like in business cards).

**Comment by bb-varun** [comment]
Hi @ValerioVillani , we have created few options for the latest updated CV's section. Please have a look and share your views.
https://www.figma.com/proto/HFh1NGT4zrR1NnBSyqx7t4/Publicv?node-id=1689%3A3385 

According to me we can go with 3rd variation of design.

**Comment by ValerioVillani** [comment]
Hi @bb-varun, Figma is telling me I don't have permission to view it.

**Comment by bb-varun** [comment]
Hi Val, Can you please share your email, I will give you the access

**Comment by ValerioVillani** [comment]
villanivalerio24@gmail.com

**Comment by ValerioVillani** [comment]
@bb-varun, I do agree, 3rd variation is perfect! Good Job.

**Comment by bb-varun** [comment]
Great. Thanks!

**Comment by bb-varun** [comment]
@duarme @vishal-bluebash, please share your opinion on the same so that we can update the same section.

**Comment by duarme** [comment]
Sorry @bb-varun and @nikita2829 I lost access, so I cannot see the proposed design, can you resume it please?

**Comment by duarme** [comment]
Valerio showed me, the 3rd variation is the best one:

<img width="282" alt="CleanShot 2021-11-22 at 14 27 47@2x" src="https://user-images.githubusercontent.com/794154/142878845-449b37ed-2670-44c9-b353-68487bc0afac.png">

But it's better to keep the profile picture on the left.

**Comment by bb-nikita** [comment]
Hello @duarme, sure will change it.

**Comment by duarme** [comment]
@simranjeetsohi the 3rd design is fine, please remember to invert the position of the image (keep it on the left). It can also be a bit bigger in order to eliminate this space:

![CleanShot 2021-11-24 at 08 56 44@2x](https://user-images.githubusercontent.com/794154/143206303-46ae0ca5-d377-47fc-b36e-db58dd5db2b3.png)

If needed, let's keep only 3 lines from the gray copy instead of 4. Don't make the copy too light, though, it must be easy to read it. A 0.7-0.6 transparency or about #666666 in hex is a good compromise.

<img width="251" alt="CleanShot 2021-11-24 at 09 01 52@2x" src="https://user-images.githubusercontent.com/794154/143207080-8d573b25-4b9c-4eb0-8fe7-2d2a8d8d5d88.png">

**Comment by simranjeetsohi** [comment]
![Screenshot 2021-11-25 at 1 37 29 PM](https://user-images.githubusercontent.com/88075579/143403268-2be97a64-50ba-42ef-a308-8ba518ae7480.png)

Hey @duarme here's the design with the changes you asked for and one thing that i didn't do was making the image bigger it wasn't possible for me because it's a circle so increasing the size would have effected the left, right and top so instead i put it in the centre of the card which now makes is more aligned

**Comment by vishal-bluebash** [comment]
@bb-nikita  I think  its fine Let's develop this and then we will see

**Comment by duarme** [comment]
Hello @bb-nikita, after seeing this in production, I have to say, the image on the right is not bad. Let's close this for now and work on something more important, such as #253 🙂
