### ISSUE TITLE
Fields of work

### ISSUE THREAD

**Issue by duarme** [publicv-org/publicv#264]
I think we could add a section here, with the job sectors:

<img width="1077" alt="CleanShot 2021-12-16 at 12 02 38@2x" src="https://user-images.githubusercontent.com/794154/146368335-095b45ad-476d-4b32-b2c5-66ae1ae34e88.png">

**Comment by duarme** [comment]
What do you think @ValerioVillani? (See the recent inquiry about "paghe e contribute" I forwarded you by email).

**Comment by ValerioVillani** [comment]
I created issue #265 that can satisfy our need to have always every course made by our Users.

Once we'll have all the courses made by our users, thanks to the skills match system, we can suggest directly the missing skill (In the Skills area).

And of course, thanks to the keyword research, if a recruiter search "Payroll", and u forgot to add payroll in your skill area, you will always be shown as possible results because of your "payroll course". (isn't it good?)

**Comment by duarme** [comment]
These should be **fields of work** (in Italian "settori lavorativi).
