### ISSUE TITLE
Subdomain not working, returning error 503

### ISSUE THREAD

**Issue by duarme** [publicv-org/publicv#268]
When I try to access to https://valeriovillani.publicv.org (or .it) I get this error:

<img width="504" alt="CleanShot 2021-12-16 at 16 05 09@2x" src="https://user-images.githubusercontent.com/794154/146406588-8cd83a95-7646-47ca-aa37-4434c7a5df10.png">

**Comment by ritik-bluebash** [comment]
Hello @duarme
I checked this issue on production. When i tried accessing the page https://publicv.org/cv/valeriovillani, it displayed unauthorized error which means the CV isn't published.
I created a new CV, When it was unpublished, i checked for **subdomain URL**, it was displaying 503 error (the same as above link). And when i published my CV, then the URL was accessible. https://ritik-233.publicv.org
I think the CV mentioned in URL isn't published that's why it isn' t accessible. Please check and let me know if the error still arises even after publishing CV.

**Comment by ValerioVillani** [comment]
@ritik-bluebash i think you're right.

Probably @duarme tried to access to my page before i published the cv (during the tests).

Let's check i now:

http://valeriovillani.publicv.it/

**Comment by duarme** [comment]
@ritik-bluebash Even so, if a CV is not published we should redirect the visitor to the homepage with a proper flash message. Sometimes the user can be the CV owner, so they also should know what's going on. I like what Twitter does, that always explains why you cannot see some content.

**Comment by duarme** [comment]
@ritik-bluebash please link the PR :)

**Comment by vishal-bluebash** [comment]
Moving to production as can not be deployed on staging
